### PR TITLE
FY2019Q4 Quarterly refresh

### PR DESCRIPTION
**Pull request by andrewconnell**
- update starter project to use latest MSAL (v3.0.8) & MS Graph SDK
- cleaned up markdown inconsistencies in lab
- added additional images to lab steps for clarification
- update lab to reflect latest MSAL & AAD portal UX
- added final solutions for the three demos, matching each exercise

### CODE REVIEW

**Comment by jasonjoh** [comment]
Hey @andrewconnell I'm running through the lab here, and in the **Provide administrative consent to application** section, I'm missing something. Step 2 says "When prompted, log in...". I ran the app and I'm not prompted for anything. I just see the home page. It looks like it's picking up that I'm authenticated in the browser, but it's failing to get the user object because of this line:

```
// Get users's email.
email = email ?? User.Identity.Name ?? User.FindFirst("preferred_username").Value;
```

It's setting `email` to the user's name ("Megan Bowen"), so when it tries to get the user by `GET /users/Megan Bowen`, that fails.

This is also causing the persona stuff to fail because the user info never gets saved in the user model cache.

**Comment by jasonjoh** [comment]
Looks like the AdaptiveCard library got updated, so now VS is giving this warning:

image

**Comment by andrewconnell** [comment]
@jasonjoh I didn't see either of these when I ran through the lab the last time before submitting the PR. Let me double check and follow up...

**Comment by andrewconnell** [comment]
@jasonjoh said:
> Looks like the AdaptiveCard library got updated, so now VS is giving this warning:

I got this fixed and included the commit above... 

Working on the other one... having a hard time duping it... still investigating...

**Comment by jasonjoh** [comment]
If it helps: I'm using Edge Dev with a profile setup for my Megan Bowen account in my test tenant. I had her logged into the AAD portal in the browser, so that may have been how it picked up that I was already authenticated.

I was able to get everything working just by changing that line to:

```
email = email ?? User.FindFirst("preferred_username").Value;
```

I can't think of a scenario where `User.Identity.Name` would ever work as the id bit for `GET /users/{id}`, unless that field sometimes has a different value?

**Comment by andrewconnell** [comment]
Same... that's exactly what I changed the code to and just verifying everything works.

**Comment by andrewconnell** [comment]
The two issues should be fixed now... ready to merge.

**Pull request merged**
